name: Create a comment on new issues

on: 
  issues:
    types: [opened]

jobs:
   comment-with-action:
      runs-on: ubuntu-latest
      steps:
        - run: echo '${{ toJSON(github.action)}}' | jq
          shell: bash
          
        - name: "dump github context"
          run: echo '${{ toJSON(github)}}' | jq
          shell: bash
      
